### ISSUE TITLE
Wallet issue

### ISSUE THREAD

**Issue by rstormsf** [enjin/Enjin-Coin-Java-SDK#1]
![photo_2019-07-31 13 29 18](https://user-images.githubusercontent.com/9360827/62245806-3741bf00-b397-11e9-866a-db6e29f5dc02.jpeg)

https://rstormsf.github.io/js-eth-personal-sign-examples/ 

click check web3 methods

https://github.com/rstormsf/js-eth-personal-sign-examples/blob/master/index.js#L13

**Comment by Favorlock** [comment]
This issue does not appear to be created in the correct repository. This repo is for the Enjin Coin Java SDK only.
